### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robertfchapman**
Various edits for sentence structure, spelling and capitalization

See paragraph two, and heading titles.

### CODE REVIEW

**Comment by pstolarz** [comment]
Thanks. Did you check the whole README? Is remaining part ok? As non English speaker I may be not aware of some language mistakes, so feel free to polish my English.

**Comment by ecnelson** [comment]
This is off-topic, but once upon a time I was porting some code for a French company. They said, the bad news is the comments are all in French, but the good news is there aren’t many of them.

Don’t ever feel bad about your English. We can sort it out.

Eric

**Comment by pstolarz** [comment]
@ecnelson As a non English speaker I can imagine that (some of) my English notes, comments  etc. may look harsh for a person using this language as a native. But I'm okay with that. It's not an essay in English I will be evaluated for on my English exam.
But if someone could fix my (at least most glaring) mistakes I'd be thankful. All of this open-source stuff bases on common effort of the community... You are good in this, I'm good with that, so let's do it together better.

**Comment by robertfchapman** [comment]
I will continue to keep an eye out,  I don't recall if I read through the whole document, but now thinking of it I'll do so.  I'm always happy to help where I can.  I also hope to contribute back to this project further, as I'm currently working on a project that will utilize this code base, and will make sure to push any additions/changes back in the hope to better your already fabulous work.  

Now after re-reading the document, I do see room for improvements and will make edits as I move forward on my project.  I'm still in the board design phase on my project, but will be testing my designs shortly when the parts and boards arrive.  

Thanks again for your contributions and hard work.

P.S. If you had a link in the README.md to make a small donation using PayPal I would be more than happy to do so.  Let me know if you need help with creating one if you so desire.

**Comment by pstolarz** [comment]
Thanks for the offer but writing this code was enough reward for me. If you would like to make some donation feel free to give some money for some local children's hospice or other charity goal.
Good luck with your project and enjoy using this module!

**Pull request merged**
