### PR TITLE
Fix build with POSIX shell and newer kernels (2017.06...)

### PR DESCRIPTION
**Pull request by pstolarz**
Hi @alukichev
Thanks for finding the issue with compilation and new kernels w1 headers. Since I was unable to raise issue for your fork I'm raising PR for my repo to pay your attention for my latest commit 1b0e0a6 solving the problem in more general way. Check if it works on your setup.

Regards!

### CODE REVIEW

**Comment by alukichev** [comment]
Hi @pstolarz !
Thank you for the module, it has saved me who knows how much time jumping around a Pi's device tree to get multimaster working. Really good work!

I was not aware that by default "issues" option in a forked repo is off. Now it's fixed in my forked repo. Sorry for the trouble.

I'll check if your patch works in my setup once I get hands on my setup in the evening, and will report it here. I suppose I should not resolve this particular PR, and you would close it instead. Am I correct?

**Comment by pstolarz** [comment]
> I suppose I should not resolve this particular PR, and you would close it instead. Am I correct?

Yes, that's correct. I decided to solve your issue in more general way, suitable for wider versions of kernels (not only the >=4.14 ones). So if you check my latest commit, let me know and I'll close this PR w/o merging.

> Thank you for the module, it has saved me who knows how much time jumping around a Pi's device tree to get multimaster working. Really good work!

I'm glad it's working for you. When I started to write the module there were no DT patching on RPi. And there was no simple way to force w1 subsystem work on the multi-master setup. After digging into w1 driver internals I quickly realized that it could be done in very simple and configurable way via w1-gpio replacement.

IMHO RPi kernel's `w1-gpio` driver has very obscure and nasty implementation - especially associated with parasite powering. If you extensively use w1 on RPi please check my [librasp](https://github.com/pstolarz/librasp) library. I hope you will enjoy it too ;) See in `./examples/dsth_*` for examples on Dallas temp sensors handling. It has very flexible and easy interface for talking with w1 subsystem via netlink, therefore it's easy to talk with arbitrary w1 device w/o writing dedicated kernel driver for it.

**Comment by alukichev** [comment]
After this change
```diff
--- a/Makefile
+++ b/Makefile
@@ -31,7 +31,7 @@ gen-mast: w1-headers
            if [ -f w1/w1_int.h ]; then \
              echo "#include \"w1/w1_int.h\"" >>$@.h; \
            else \
-             echo "#include \"w1/w1.h\"" >>$@.h; \
+             echo "#include <linux/w1.h>" >>$@.h; \
            fi; \
            echo >>$@.h; \
            pf="st";; \
```
your patch works in my setup.

**Comment by pstolarz** [comment]
How do you compile the module: by cross-compiler on directly on RPi? Did you set KERNEL_SRC env? Was the `w1` link set by the Makefile? Could you provide Makefile'c compilation output?

I tested the cross-compilation for latest 4.14 RPi kernel and haven't encountered any problems (although didn't test on RPi, since I rarely compile directly on the device).

**Comment by pstolarz** [comment]
I also realized, that you may encounter the problem, as `w1` link was present during the compilation. `rm ./w1` or `make distclean` and try again.

**Comment by alukichev** [comment]
Sorry for the late reply, I could not easily get my hands on the original environment.

> How do you compile the module: by cross-compiler on directly on RPi? Did you set KERNEL_SRC env? 

  [user@environment w1-gpio-cl ((0c0e044...))]$ KERNEL_SRC=../kernel/rpi-kernel ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- CONFIG_W1_MAST_MAX=20 make

> Was the w1 link set by the Makefile? Could you provide Makefile'c compilation output?

Apparently. I cannot now reproduce the output then, as I have removed the original link and don't think it's relevant now. The thing is that if it is "broken" then the build will fail.

Removing the link and running the above command again produces a module without errors in my environment.

**Comment by pstolarz** [comment]
Thanks for the test Alexander, so I'm closing the PR...

**Pull request closed without merging**
